### ISSUE TITLE
issue at step9ts. I tried to change testnet to mainnet for step9 and always get error: wallet is not deployed. All steps before works, whats the deal

### ISSUE THREAD

**Issue by Datsunco** [ton-community/tutorials#16]

**Comment by alexpaniman** [comment]
I have the same issue. Were you able to resolve?

All the steps before 9th worked, even getting correct balance of the wallet on the testnet. I thought my wallet was deployed when I created it on my phone via Tonkeeper.

**Comment by sidewapboss** [comment]
You should first make a send transaction from the wallet to get it mounted and deployed to the blockchain else you would face this issue.

**Comment by sidewapboss** [comment]
I have implemented this on a project even went to the point of getting bulk transactions and also single transactions more like transaction history, I don't mind sharing my code
