### ISSUE TITLE
Error with build.sh

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/tutorials#21]
`Build.sh` contains "npm run watch,":

![CleanShot 2023-05-11 at 16 02 39@2x](https://github.com/ton-community/tutorials/assets/5148967/bd3c8ffe-044c-4efb-bea0-0fa9e70e23c7)

But no "watch" command is provided in "package.json".

![CleanShot 2023-05-11 at 16 02 18@2x](https://github.com/ton-community/tutorials/assets/5148967/efa52643-1c28-47ab-bd02-74e7905f8380)

So I can't run the project locally

**Comment by shaharyakir** [comment]
Fixed by a3e897a686037ee5dfc3c21e1c5d6a7c6baeeb41
