### ISSUE TITLE
How to get NFT from TON masters in mainnet?

### ISSUE THREAD

**Issue by zjor** [ton-community/tutorials#34]
I followed the `01-wallet` tutorial but did everything in mainnet.
I send 0.05 TON to `EQChHpu8-rFBQyVCXJtT1aTwODTBc1dFUAEatbYy11ZLcBST` address.
Will I have an NFT minted to my address? (`EQC5Bjo-w76nmo-yc_QhV1JkWOAO9et65s5Oh6zUMIgK41Zy`)

**Comment by roma-marshall** [comment]
hello @zjor,
you sent it to the wrong address. You should send it to: `EQA4V9tF4lY2S_J-sEQR7aUj9IwW-Ou2vJQlCn--2DLOLR5e`

source: (Step 9) https://ton-community.github.io/tutorials/01-wallet/
